### ISSUE TITLE
Template Not Imported

### ISSUE THREAD

**Issue by Tigerteron** [Ciacho/zabbix-templates#1]
Hi Dear,
I checked template, your export has missing some tags like  snmp_community, history,                trends,status,value_type,allowed_hosts,...
then i Could not import template
please check it
thanks a lot

**Comment by Ciacho** [comment]
Hi,
I checked on two independent zabbixes (4.4.x) - in both cases template (stable and devel) imported without problems.

Can you paste the full error message?

**Comment by Tigerteron** [comment]
Hi,
My zabbix version is 4.2.8
![Annotation 2020-01-20 111617](https://user-images.githubusercontent.com/49148135/72707715-56ffb600-3b76-11ea-82ca-1c2f566aba37.jpg)

**Comment by Ciacho** [comment]
I checked the template for version 4.4. Prepare a version for older servers :)

**Comment by Tigerteron** [comment]
thanks buddy

**Comment by Ciacho** [comment]
Zabbix 4.4 has changed the way you save templates :)

I made a new version of the template - it works on 4.0 and 4.2.

**Comment by Tigerteron** [comment]
Thanks buddy I finally imported Successfully

**Comment by Tigerteron** [comment]
Dear Ciacho,
I had several hours to fix problem server url item in your template 

web.page.get[{$SVC_PDNS_SERVER_IP},/,{$SVC_PDNS_SERVER_PORT}]
that is incorrect because additional "/" 
and correct type of its:
web.page.get[{$SVC_PDNS_SERVER_IP},,{$SVC_PDNS_SERVER_PORT}]
thanks a lot
best regrads

**Comment by Ciacho** [comment]
Documentation zbx 4.2.x:
web.page.get[host,<path>,<port>] 
URL Path for webserver is /:
T 127.0.0.1:51536 -> 127.0.0.1:8081 [AP]
  GET / HTTP/1.1..Host: 127.0.0.1:8081..User-Agent: Zabbix 4.4.4..Accept: */*.... 

For example: 
telnet localhost 8081
GET / HTTP/1.0


But - what You have on {SVC_PDNS_SERVER_IP} - i use loopback address - 127.0.0.1.
