### ISSUE TITLE
Not working with zabbix 5

### ISSUE THREAD

**Issue by razerrazer** [Ciacho/zabbix-templates#2]
Hi,

This template is unfortunately not working with zabbix version 5. 

No latest data are displayed for the host.

**Comment by Ciacho** [comment]
Are there any errors in the server logs?
Can you do curl http://127.0.0.1:8081 from the server level?
(or any other IP and PORT address you have defined in the macro)


I use this template on zabbix 5.0 myself - and it works fine.

Alternatively, in item pdns_server you need to change the "History storage period" field to eg 1d and see if it is being downloaded.
If it doesn't download, the problem is with the webserver in pdns_server.

**Comment by razerrazer** [comment]
Yes curl works fine on the server, I get a lot of information if i type the command "curl http://127.0.0.1:8081"

#netstat -tulpn | grep '8081'
tcp        0      0 127.0.0.1:8081          0.0.0.0:*               LISTEN      5084/pdns_server   
 
cat /etc/pdns/pdns.conf | grep 'webserver'
webserver=yes
webserver-address=127.0.0.1
webserver-allow-from=127.0.0.1,::1
webserver-port=8081



![Screenshot at 2020-10-14 13-48-25](https://user-images.githubusercontent.com/17000974/95984826-13478d80-0e24-11eb-9d17-e90e738c5b08.png)

![Screenshot at 2020-10-14 13-50-34](https://user-images.githubusercontent.com/17000974/95984967-40943b80-0e24-11eb-9bd8-30bae8b75696.png)


I did try to change History storage period but it did nothing unfortunately.

Also the log from zabbix with debug = 4 giving nothing, it feels like it didn't try to run these commands.

**Comment by razerrazer** [comment]
Do you have a clue ?

**Comment by Ciacho** [comment]
I checked again, imported the zabbix 4.4 version and it works fine for me.

![Zrzut ekranu z 2020-10-15 16-18-41](https://user-images.githubusercontent.com/271741/96143639-91c72c80-0f03-11eb-9f5b-614b5111ecd5.png)

Do you have other active checks on the ns3 server that are working? Maybe the problem is with the communication from NS3 to the zabbix server? Remember that active checks require reverse communication, and my templates are active checks as standard.

**Comment by razerrazer** [comment]
Hm every other template is working :/

![Screenshot at 2020-10-15 16-31-03](https://user-images.githubusercontent.com/17000974/96144050-069a6680-0f04-11eb-8be9-1dfeb99bb6ed.png)

This is the current agent version i have on the node : 
@ns3 ~]# zabbix_agentd -V
zabbix_agentd (daemon) (Zabbix) 5.0.4
Revision 69c0ad3686 28 September 2020, compilation time: Sep 28 2020 12:28:14

Copyright (C) 2020 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 1.0.2k-fips  26 Jan 2017
Running with OpenSSL 1.0.2k-fips  26 Jan 2017

And this is the zabbix-server version:

zabbix02 ~]# zabbix_server -V
zabbix_server (Zabbix) 5.0.4
Revision 69c0ad3686 28 September 2020, compilation time: Sep 28 2020 15:30:12

Copyright (C) 2020 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 1.1.1c FIPS  28 May 2019
Running with OpenSSL 1.1.1c FIPS  28 May 2019

**Comment by Ciacho** [comment]
Are these metrics also active checks? (click 'show details' on top page)

**Comment by razerrazer** [comment]
aha, no none of them is active checks unfortunately. (so here is the problem for sure!)

They are Zabbix agent or Dependent item  / Calculated

Just one question, could it have something to do with ServerActive= in zabbix configuration for the agent ?

Thank you for your help btw :)

**Comment by Ciacho** [comment]
Configuratively, yes - 'ServerActive' must be set
but in addition, network communication from the monitored server to the zabbix server must be improved (standard port 10051)

Active checks are much more efficient than passive ones - in terms of network traffic, monitored server load, etc.

https://www.zabbix.com/documentation/current/manual/appendix/items/activepassive

**Comment by razerrazer** [comment]
Hi,

I get it working finally, i have found out after i activated serverchecks that my hostname on the configuration was the issue, and it was not the same as for the host in zabbix, now i'm getting in data from the host.

![Screenshot at 2020-10-15 17-14-20](https://user-images.githubusercontent.com/17000974/96149673-e1a8f200-0f09-11eb-80ab-ec8cf7d9a493.png)

Thank you so much =)
